//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTerritory
    {
        public int PersonID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Territorio { get; set; }
    }
}
